import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";
import NotifyScript from "./components/NotifyScript";

// Font files can be colocated inside of `app`
const fa = localFont({
  src: [
    {
      path: "./fonts/fa-regular-400.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/fa-regular-400.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/fa-brands-400.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/fa-brands-400.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/fa-solid-900.woff2",
      weight: "900",
      style: "black",
    },
    {
      path: "./fonts/fa-solid-900.ttf",
      weight: "900",
      style: "black",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
        <Script src="/assets/js/custom.js" strategy="afterInteractive" />
        <NotifyScript />
      </body>
    </html>
  );
}
